export const labels: Record<string, string> = {
  ORDER_PREPARATION_STARTED: 'Préparation commencée',
  ORDER_READY_TO_SHIP: 'Commande prête à expédier',
  ORDER_SHIPPED: 'Commande expédiée',
  ORDER_DELIVERED: 'Livraison confirmée manuellement',
  SHIPMENT_CREATED: 'Expédition créée',
  SHIPMENT_UPDATED: 'Brouillon d’expédition modifié',
  SHIPMENT_TRACKING_UPDATED: 'Suivi corrigé',
  EMAIL_RETRY_REQUESTED: 'Nouvelle tentative d’email demandée',
  UNFULFILLED: 'À préparer',
  PREPARING: 'En préparation',
  READY_TO_SHIP: 'Prête à expédier',
  SHIPPED: 'Expédiée',
  DELIVERED: 'Livrée',
  PENDING: 'En attente',
  SENDING: 'Envoi en cours',
  SENT: 'Envoyé',
  DRAFT: 'Brouillon',
  QUEUED: 'En file',
  COMPLETED: 'Terminée',
  SKIPPED: 'Ignoré',
  ACTIVE: 'Actif',
  UNSUBSCRIBED: 'Désinscrit',
  ARCHIVED: 'Archivé',
  PENDING_PAYMENT: 'En attente de paiement',
  PAYMENT_PROCESSING: 'Paiement en cours',
  PAID: 'Payée',
  PAYMENT_FAILED: 'Paiement échoué',
  PAYMENT_REVIEW: 'À vérifier',
  CANCELLED: 'Annulée',
  CANCELED: 'Annulé',
  REFUNDED: 'Remboursée',
  PARTIALLY_REFUNDED: 'Remboursement partiel',
  REFUND_REQUESTED: 'Remboursement demandé',
  REFUND_SUCCEEDED: 'Remboursement effectué',
  REFUND_FAILED: 'Remboursement refusé',
  EXPIRED: 'Expirée',
  REQUIRES_PAYMENT_METHOD: 'Moyen de paiement attendu',
  REQUIRES_ACTION: 'Authentification attendue',
  PROCESSING: 'En cours',
  SUCCEEDED: 'Réussi',
  FAILED: 'Échoué',
  CONSUMED: 'Consommée',
  RELEASED: 'Libérée',
  RESERVED: 'Réservée',
  RETURN_STATE_REQUESTED: 'À examiner',
  RETURN_STATE_APPROVED: 'Accepté',
  RETURN_STATE_RECEIVED: 'Colis reçu',
  RETURN_STATE_REFUNDED: 'Remboursé',
  RETURN_STATE_REJECTED: 'Refusé',
  RETURN_STATE_CANCELED: 'Clos',
  INVOICE_ISSUED: 'Facture émise',
  TAX_SETTINGS_UPDATED: 'Réglages fiscaux modifiés',
  INVOICE_SETTINGS_UPDATED: 'Mentions de facture modifiées',
  RETURN_CREATED: 'Retour créé',
  RETURN_APPROVED: 'Retour accepté',
  RETURN_REJECTED: 'Retour refusé',
  RETURN_RECEIVED: 'Colis de retour reçu',
  RETURN_CANCELED: 'Retour clos',
  PROMO_ACTIVE: 'Actif',
  PROMO_SCHEDULED: 'Programmé',
  PROMO_EXPIRED: 'Expiré',
  PROMO_EXHAUSTED: 'Épuisé',
  PROMO_DISABLED: 'Désactivé',
  PROMOTION_CREATED: 'Code promo créé',
  PROMOTION_UPDATED: 'Code promo modifié',
  PROMOTION_DELETED: 'Code promo supprimé',
  RESTOCK: 'Réapprovisionnement',
  CORRECTION: 'Correction',
  DAMAGE: 'Dommage',
  LOSS: 'Perte',
  RETURN: 'Retour',
  MANUAL: 'Manuel',
  BOOSTER: 'Booster',
  BLISTER: 'Blister',
  TRIPACK: 'Tripack',
  BUNDLE: 'Bundle',
  DISPLAY: 'Display',
  ETB: 'Coffret Dresseur Élite',
  COLLECTION_BOX: 'Coffret collection',
  TIN: 'Boîte métal',
  DECK: 'Deck',
  ACCESSORY: 'Accessoire',
  SINGLE_CARD: 'Carte à l’unité',
  OTHER: 'Autre',
  FR: 'Français',
  EN: 'Anglais',
  JP: 'Japonais',
  DE: 'Allemand',
  ES: 'Espagnol',
  IT: 'Italien',
  NEW: 'Neuf',
  PRODUCT_CREATED: 'Produit créé',
  PRODUCT_UPDATED: 'Produit modifié',
  PRODUCT_STATUS_CHANGED: 'Publication modifiée',
  VARIANT_CREATED: 'Variante créée',
  VARIANT_UPDATED: 'Prix / variante modifiés',
  STOCK_ADJUSTED: 'Stock ajusté',
  IMAGE_UPLOADED: 'Image ajoutée',
  IMAGE_UPDATED: 'Image modifiée',
  IMAGE_REMOVED: 'Image retirée',
  CATEGORY_SAVED: 'Catégorie enregistrée',
  SET_SAVED: 'Extension enregistrée',
  GAME_SAVED: 'Jeu enregistré',
  ORDER_NOTE_UPDATED: 'Note interne modifiée',
  ORDER_CANCELLATION_REQUESTED: 'Annulation demandée',
  ORDER_CANCELLATION_RESULT: 'Résultat d’annulation',
  SUPPLIER_SAVED: 'Fournisseur enregistré',
  SUPPLIER_PROFILE_DELETED: 'Profil de fichier supprimé',
  SUPPLIER_PAGE_AI: 'Page de catalogue envoyée à l’IA',
  SUPPLIER_IMPORT_APPLIED: 'Import fournisseur appliqué',
  SUPPLIER_IMPORT_REVERTED: 'Import fournisseur défait',
  SUPPLIER_IMPORT_CANCELED: 'Import fournisseur abandonné',
  IMPORT_UPLOADING: 'Envoi en cours',
  IMPORT_EXTRACTING: 'Lecture en cours',
  IMPORT_MAPPING: 'Colonnes à valider',
  IMPORT_REVIEW: 'Aperçu à valider',
  IMPORT_APPLIED: 'Importé',
  IMPORT_REVERTED: 'Défait',
  IMPORT_CANCELED: 'Abandonné',
  IMPORT_FAILED: 'Échec',
  ROW_CREATE_PRODUCT: 'Nouveau produit (brouillon)',
  ROW_CREATE_OFFER: 'Nouvelle offre',
  ROW_UPDATE_OFFER: 'Offre mise à jour',
  ROW_UNCHANGED: 'Inchangée',
  ROW_REVIEW: 'À vérifier',
  ROW_REJECT: 'Rejetée',
  ROW_IGNORE: 'Ignorée',
  MATCH_CERTAIN: 'Correspondance certaine',
  MATCH_PROBABLE: 'Correspondance probable',
  MATCH_NEW: 'Nouveau produit',
  MATCH_AMBIGUOUS: 'Ambiguë',
  MATCH_INVALID: 'Inexploitable',
  CHANGE_NEW_OFFER: 'Nouvelle référence',
  CHANGE_PRICE_DOWN: 'Prix en baisse',
  CHANGE_PRICE_UP: 'Prix en hausse',
  CHANGE_BACK_IN_STOCK: 'De retour en stock',
  CHANGE_OUT_OF_STOCK: 'Plus en stock',
  CHANGE_STOCK: 'Stock modifié',
  CHANGE_DISAPPEARED: 'Disparue du catalogue',
  CHANGE_REAPPEARED: 'De retour au catalogue',
  CHANGE_RELEASE_DATE: 'Date de sortie modifiée',
  CHANGE_PACKAGING: 'Conditionnement modifié',
  CHANGE_INFO: 'Information modifiée',
  AVAIL_IN_STOCK: 'En stock',
  AVAIL_OUT_OF_STOCK: 'Rupture',
  AVAIL_PREORDER: 'Précommande',
  AVAIL_ON_ORDER: 'Sur commande',
  AVAIL_DISCONTINUED: 'Arrêté',
  AVAIL_UNKNOWN: 'Inconnue',
  OFFER_ACTIVE: 'Au catalogue',
  OFFER_MISSING: 'Absente du dernier catalogue',
  PAGE_PENDING: 'OCR en attente',
  PAGE_DONE: 'Lue',
  PAGE_NEEDS_REVIEW: 'À vérifier',
  PAGE_FAILED: 'Échec de lecture',
  PAGE_IGNORED: 'Ignorée',
  METHOD_TEXT: 'Texte du PDF',
  METHOD_OCR: 'OCR local',
  METHOD_AI: 'IA',
  FULL: 'Catalogue complet',
  PARTIAL: 'Extrait',
};
export function label(value: string) {
  return labels[value] ?? value;
}
export function formatDate(value: Date | string | null) {
  return value
    ? new Intl.DateTimeFormat('fr-FR', {
        dateStyle: 'medium',
        timeStyle: 'short',
        timeZone: 'Europe/Paris',
      }).format(new Date(value))
    : '—';
}
export function euros(value: { toString(): string } | number | null) {
  return value === null
    ? '—'
    : new Intl.NumberFormat('fr-FR', {
        style: 'currency',
        currency: 'EUR',
      }).format(Number(value.toString()));
}
export function dateInput(value: Date | null | undefined) {
  return value?.toISOString().slice(0, 10) ?? '';
}
